### ISSUE TITLE
Make workload 'sticky' 

### ISSUE THREAD

**Issue by dhrp** [nerdalize/nerd#131]
When a user has created a workload, (or do anything else) on a workload, it would be nice if the workload would be sticky. It will be a more smooth UX

e.g.
```
$ nerd workload set asd987f6sa

nerd dataset upload ~/Data
nerd task create -- blah1
nerd task create -- blah2

nerd task list
```

notice I didn't have to copy-paste the workload ID every time.

**Comment by alexanderweiss** [comment]
+1
This is quite a big thing in documentation and showing how 'easy' Nerd is.
Right now this requires quite a few lines of both input and output code and it can't just be copied and pasted because the user has to put in the right id's.

**Comment by advanderveer** [comment]
Nerd projects are already "sticky", adding an additional layer of stickyness will be confusing. Instead milestone 1.1 will allow you to specify custom names for job running. This makes it easier for users to remember and allows us to make the docs copy friendly.
