### ISSUE TITLE
Provide a simple & quick way to run through the complete workflow

### ISSUE THREAD

**Issue by alexanderweiss** [nerdalize/nerd#137]
It'd be really nice to be able to run through the complete workflow of uploading data, starting a workload, starting a task and downloading data using a single command (or a single line at least).

So either something like:
~~~
nerd run nerdalize/wgetworker ./my-input-data ./my-output-data -- some-command
~~~

Or possibly by adding some sort of await command that waits for a specific task to finish in combination with piping:
~~~
nerd dataset upload ./my-input-data | nerd workload start nerdalize/wgetworker | nerd task start www.nerdalize.com | nerd task await | nerd dataset download ./my-output-data
~~~

That would allow super-straightforward, one-line examples that are easy to copy-paste.

**Comment by advanderveer** [comment]
This is cool, i'm adding this proposal to the next milestone once we'll be working with datasets
