### ISSUE TITLE
Set default project after login

### ISSUE THREAD

**Issue by dhrp** [nerdalize/nerd#142]
To make it more straightforward, after a users (first) login we should automatically 'nerd project set org-Default'

**Comment by advanderveer** [comment]
Consider adding this to the next milestone if its possible to guess the default project during login sequence by just appending "-default" to the users organization. @dhrp  @neoel will this be true for the foreseeable future?

**Comment by dhrp** [comment]
well; you don't have (know) a user's organization. It would make more sense to add a field to the user profile (https://auth.nerdalize.com/v1/users/me/). You could fetch this.
