### ISSUE TITLE
Allow users to give names to datasets, tasks & workloads

### ISSUE THREAD

**Issue by alexanderweiss** [nerdalize/nerd#143]
Allow users to optionally pass a name or label when creating datasets, tasks & workloads that can be used as an alternative to the id when referencing it later.

**Comment by LilliJane** [comment]
We could also use the names generator from [Moby](https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go) to get a random name if they don't precise any label, it would still be easier to use than the id.

**Comment by advanderveer** [comment]
Closing this, it is covered in the job running and dataset milestones
