### ISSUE TITLE
Check if an ID is valid

### ISSUE THREAD

**Issue by LilliJane** [nerdalize/nerd#156]
If I want to describe a task with wrong IDs, I get the following output which is not clear (did something went wrong with my task?):
```
$ nerd task describe 0123456789 1503485716536681545                  
Workload Details:
ID:         0
Cmd:        []
OutputID:   
Status:     
Created:    a long while ago

```

**Comment by advanderveer** [comment]
We'll be allowing users users to provide a custom names for the next milestone, this should make confusion preventable but will not make it possible to check if the name is valid on the client side. That being said, an error will be returned from the server when a job does not exists with a given name
