### ISSUE TITLE
nerd workload describe unclear

### ISSUE THREAD

**Issue by LilliJane** [nerdalize/nerd#161]
When we run `nerd workload describe <workload_id>`, the output is not really clear about the workers:
```bash
ID:         <workload_id>
Image:      quay.io/nerdalize/delft3d
Input:         
Created:    a few minutes ago
Workers:    worker-id-from_kubernetes (PENDING)
```
It is unclear for the user that `workers` means `worker id`.
One solution would be to rename `Workers` by `WorkersID` or to create a table like this:
```bash
ID:         <workload_id>
Image:      quay.io/nerdalize/delft3d
Input:         
Created:    a few minutes ago

Workers:    
ID                         STATUS
worker-id-from_kubernetes  PENDING
```

**Comment by advanderveer** [comment]
Closing, this will be improved through the use of jobs in the next milestone
