### ISSUE TITLE
nerd 0.5.7 doesn't work as worker

### ISSUE THREAD

**Issue by dhrp** [nerdalize/nerd#167]
We discovered that there is an issue with nerd worker work, using nerd version 0.5.7. nerd version 0.5.4 does (still) work though. 

More investigation needed.

root@a5dc3f3f7296:/delft3d/examples/01_standard# nerd workload list
You are not logged in. Please login using 'nerd login'

**Comment by advanderveer** [comment]
Closing this as we're moving to a worker less setup in the next milestone
