### ISSUE TITLE
login redirect always goes to production authentication

### ISSUE THREAD

**Issue by dhrp** [nerdalize/nerd#177]
As first described in https://github.com/nerdalize/authentication/issues/146, when a user logs in to a different environment (e.g. staging) it will still be redirected to the production endpoint: https://auth.nerdalize.com/do/login_complete/?client=CLI. 

This is not entirely nice. It would be better if the base URL would be fetched out of .nerd/config.json

**Comment by LilliJane** [comment]
Can we close this issue @advanderveer? We now have the possibility to configure the endpoints using `NERD_ENV`
