### ISSUE TITLE
nerd project set does not provide feedback on succes

### ISSUE THREAD

**Issue by matesitox** [nerdalize/nerd#180]
using nerd-0.5.8-linux when doing `nerd project set <project-name>` I get no feedback on whether the project is currently set, this leaves me in doubt whether that action succeeded.

![image](https://user-images.githubusercontent.com/1717667/32046506-9569275c-ba43-11e7-9b46-83914b1fa1eb.png)

**Comment by advanderveer** [comment]
We're planning to check if the required namespace for a project exists upon using the `project set` command. This way we can immediately test if the connection is working and if the namespace is ready to go. If its not we want to prvent the user from changing into a project that wont work. If it does we can provide the user with nice feedback.
