### ISSUE TITLE
Investigate how a Job can be stopped

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#197]
Users would like to prevent a Job from consuming resources, deletion of Jobs is kind of a blunt weapon as the user might still want to investigate its output or logs. Research needs to be done in order to know how this might help.

**Comment by LilliJane** [comment]
One option would be to use the `parallelism` spec and set it to 0.
From the Kubernetes [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism):  "The requested parallelism (.spec.parallelism) can be set to any non-negative value. If it is unspecified, it defaults to 1. If it is specified as 0, then the Job is **effectively paused** until it is increased."

**Comment by advanderveer** [comment]
There is an interesting discussion here on how to use backoff and restart policies to stop a job: https://github.com/kubernetes/community/pull/583

**Comment by LilliJane** [comment]
Another option, as Job are supposed to be ran to completion, would be to keep the job template in the `~/.nerd` directory. 
The user could save a job template in multiple ways, when the user starts, stops or deletes a job. `nerd job start|stop|delete <args> --save`
The user could also list and describe templates and reuse them whenever they want. `nerd template list|describe|delete` (not sure about the necessity to create a template command)
Then `nerd job start --template name.yaml`

This could be interesting for users that want to switch to kubectl, and they would already have their own job manifests.

**Comment by LilliJane** [comment]
So after some tests, parallelism set to 0 is not really what we need. Indeed, it deletes the running pod, meaning that we loose its logs, events and statuses.

The backoffLimit and backoffSeconds could be really useful as it would let  users specify how many times they want their job to retry in case of failure. Only problem is that this feature is only available from Kubernetes v1.8

**Comment by advanderveer** [comment]
For the first milestone we will "stop" a job by reducing its parallelism to 0. This effectively removes the pod so no logs are available to the user but it will no longer consumer resources
