### ISSUE TITLE
Listing jobs on a non-existing namespace should return an error

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#208]
## Expected Behavior
```
nerd job list --namespace=bogus
error: failed to run job: the project does not exist
`

## Actual Behavior
```
nerd job list --namespace=bogus
JOB   IMAGE   CREATED AT   PHASE   DETAILS 
`

## Design
this is somewhat complicated as the listing function of kubernetes doesn't take this into account at all. So we need to test for ourselves. This introduces a new call "describe namespace" that can fail for other reasons (no access to the namespace)

**Comment by LilliJane** [comment]
I don't know if it's still relevant as we don't have the `--namespace` flag for the nerd job run command, but we could check if the namespace exists when the project is set by getting the namespace:

![screenshot_20180122_130108](https://user-images.githubusercontent.com/7657393/35219831-6d99094c-ff74-11e7-8ead-965e0e441ba4.png)
