### ISSUE TITLE
When a user has nog logged in show descriptive error

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#222]
## Expected Behavior
When a user has not logged in but runs a command that requires the user to be logged in give a descriptive error

## Actual Behavior
it shows:
error: failed to configure: failed to build Kubernetes config from provided kube config path: stat /Users/adam/.kube/config: no such file or directory

but might also occur in other cases?

## Steps to Reproduce the Problem

  1. mv ~/.kube/config to another place
  w. run nerd run

**Comment by LilliJane** [comment]
How about we add an if statement in the pkg/populator/populator.go at the place that the kube config file is opened and check fi the correct key is present. If not return ErrAuthInfoMissing and handle this gracefully in the command
