### ISSUE TITLE
Settle on --input --output format

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#262]
## Expected Behavior
Currently (as a first draft) the --input and --output format are specified in the same way docker does this (using a colon). Currently, the to left to right format was proposed but this might confuse people.

- Maybe make container side of volume expicit
- Have consistent order for both --input and --output

**Comment by advanderveer** [comment]
After some discussion we settled on not changing the format for now, making it more explicit makes it very verbose. There is probably a better way but we will not try to solve this for the current milestone

**Comment by LilliJane** [comment]
Maybe we could close this issue, except if you @advanderveer and @alexanderweiss have another idea?

**Comment by alexanderweiss** [comment]
We've settled on something for now. So I'm okay with closing it 😃.
