### ISSUE TITLE
Rollback ad-hoc datasets on job running

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#263]
Whenever a job is created with datasets that were not there previously we would like to rollback the creation whenever the job cannot be created (because a job with the name already exists)

**Comment by LilliJane** [comment]
Should we remove the input dataset if the upload was successful?

**Comment by Overv** [comment]
I think a system like that can only be implemented as soon as we can ensure that a dataset is no longer used by any other jobs.

**Comment by LilliJane** [comment]
This issue is about datasets that were created using the `nerd job run` command, so they cannot be in use by other jobs

**Comment by LilliJane** [comment]
We could delete the output one and keep the input one. We should also give a hint for the user on how to reuse it.
