### ISSUE TITLE
Refactor transfer library for production use

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#284]
Current transfer library is not suitable for production:

- [x] Should support uploading/downloading of nested folder structures #274 
- [x] Should not have has duplicate bucket configuration
- ~~Should not require large temporary files (#254), we'll switch to a .tar~~ turns out this is inevitable
- [x] Should be tested make sure we have test case that tests the flex volume: #271 
- Should The upload/download to the user's desktop should retry though disconnects: #269 
- Should make use of temporary download folder: #268 
- Should allow for progress updates for #184

**Comment by Overv** [comment]
Could also take care of #239
