### ISSUE TITLE
Flex volume is currently hardcoded to 100 MB

### ISSUE THREAD

**Issue by Overv** [nerdalize/nerd#290]
The size of flex volumes is currently hardcoded in a constant:

https://github.com/nerdalize/nerd/blob/v2/cmd/flex/main.go#L73

For the public launch it would be nice to have a different solution like specifying it as part of the pod resource limits or the dataset resource metadata. If this is not feasible given the time we have, then it should at least be hardcoded to a more sensible size for our customers.

**Comment by advanderveer** [comment]
It might be worth to note that there is currently a limit of 5GB (#298) for the maximum size a anonymous user can upload. There is also an issue that covers giving feedback to the user when its upload is to large #265
