### ISSUE TITLE
Ctrl + c while uploading does not remove temporary file

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#296]
## Expected Behavior
Whenever a large file is being uploaded it might be possible that the user cancels the upload, in which case pressing ctrl+c should allow for gracefull shutdown of the upload (and deleting the temporary file)

Also, it doesn't remove the dataset, resulting in an empty (0B) dataset remaining

**Comment by Overv** [comment]
The temporary file could be created, opened for reading/writing then immediately deleted from the file system. The file handle in the program itself will then be the only reference and the file will be automatically deleted by the OS when the program exits or closes the handle. It doesn't matter if the program gracefully exits or crashes.

**Comment by advanderveer** [comment]
@Overv  thats cool! Didn't know that was possible, i'm gonna use that as an approach
