### ISSUE TITLE
Progress bar is unpredictable

### ISSUE THREAD

**Issue by LilliJane** [nerdalize/nerd#301]
On Linux:
- ![image](https://user-images.githubusercontent.com/7657393/36547342-f7ca6340-17ed-11e8-86ca-78e03dba3b70.png)
- ![image](https://user-images.githubusercontent.com/7657393/36547402-193054c2-17ee-11e8-968e-0912e9658e17.png)

On Windows:
- Powershell: ![image](https://user-images.githubusercontent.com/285063/36547487-4a242478-17ee-11e8-9dfc-47a185a3edf6.png)
- Cygwin: ![image](https://user-images.githubusercontent.com/285063/36547593-821ceb6c-17ee-11e8-8f43-b9cb97443c46.png)

**Comment by Overv** [comment]
TODO: separate visual issues like progress bar not appearing and final size being wrong

**Comment by advanderveer** [comment]
The terminal rendering is a known problem with the progress bar library which we won't fix at this point  as it is specific and not very breaking. The inconsistent percentage is fixed
