### ISSUE TITLE
Logs unavailable when job fails (in some cases?)

### ISSUE THREAD

**Issue by alexanderweiss** [nerdalize/nerd#309]
Job failed, then getting logs failed, then getting logs succeeded, then job remained failed (or failed again, not sure, but listing still showed failed)

~~~
 ~  nerd job list
To see the logs of a job, use: `nerd job logs <JOB-NAME>`
JOB            IMAGE                      INPUT   OUTPUT   MEMORY   VCPU   CREATED AT       PHASE    DETAILS   
my-first-job   nerdalize/co2-calculator                    3Gi      2      55 seconds ago   Failed             
 ~  nerd job logs my-first-job
error: failed to fetch job logs: cluster failed to perform action: container "main" in pod "nlz-nerdmy-first-job-m6hsh" is waiting to start: ContainerCreating
~~~

**Comment by advanderveer** [comment]
Also, it seems to cycle between states:

Job goes to failed, then running nerd job logs returns “ error: failed to fetch job logs: cluster failed to perform action: container "main" in pod "nlz-nerdj-2mlcj-p2585" is waiting to start: ContainerCreating“ Then running it again a little later returns “-- no visible logs returned
