### ISSUE TITLE
Facilitate a way to delete many jobs (and maybe datasets)

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#314]
It should be easy to delete a whole bunch of jobs and datasets:

"Boris: would be nice to have a -q option for nerd job list that only returns the IDs. This way you can easily delete multiple jobs"

We have several options
- Support a -q option and allow the `nerd job delete` and `nerd dataset delete` to take multiple ids/names from stdin?
- Support a --all like kubectl? blunt weapon? ask for confirmation?
- Maybe support some pattern matching for the listing option? or for deletion?

**Comment by LilliJane** [comment]
Now we can delete multiple datasets or jobs at the same time by providing a list of ids (pull request #335). The pull request #347 allows people to use a `-a` or `--all` option to delete all datasets or jobs at the same time
