### ISSUE TITLE
Improve dataset handling errors

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#319]
Errors from the transfer package can be quite cryptic:

- "Dataset error messages are not very friendly “error: failed to create transfer handle: failed to create dataset resource: datasets.stable.nerdalize.com "nlz-nerdflights" already exists”” "
- "If a dataset with the given name already exists I get this (ugly) error message: error: failed to create transfer handle: failed to create dataset resource: datasets.stable.nerdalize.com "nlz-nerdflights" already exists"

Find common usecases and return a more friendly message

**Comment by LilliJane** [comment]
If we try to download a dataset that is not yet uploaded to s3, we get a quite unfriendly error:
![image](https://user-images.githubusercontent.com/7657393/36791587-868fb0ae-1c98-11e8-9d7a-1c64919a1db0.png)
