### ISSUE TITLE
nerd job delete accepts multiple job names, but only handles the first one

### ISSUE THREAD

**Issue by Overv** [nerdalize/nerd#333]
## Expected Behavior

When running `nerd job delete job1 job2 job3`, I either expect to receive an error stating that only one job can be deleted at a time or that it deletes all specified jobs.

## Actual Behavior

```
$ nerd job delete job1 job2
Deleted job: 'job1'
To see whats happening, use: 'nerd job list'
```

## Steps to Reproduce the Problem

  1. Run `nerd job delete` with multiple job names

## Specifications

  - Version (using `nerd version`): 1.0.0-alpha1 (965ab1c)
  - Platform: Windows 10 x64
  - Subsystem: Command Prompt

## Anything else we need to know?

-

**Comment by LilliJane** [comment]
Mix of the issues about the number of arguments (#323) and about the deletion of multiple datasets/jobs at the same time (#314)

**Comment by Overv** [comment]
Duplicate of #323
