### ISSUE TITLE
Change help text for `nerd job run`

### ISSUE THREAD

**Issue by borismattijssen** [nerdalize/nerd#353]
## Expected Behavior
`nerd job run -h` should say that the `--output` option has the format `<DATASET_NAME>:<JOB_DIR>`

## Actual Behavior
`nerd job run -h` says that the `--output` option has the format `<DIR>:<JOB_DIR>`

## Steps to Reproduce the Problem

  1. Change the word ;)

## Specifications

  - Version (using `nerd version`):  1.0.0-alpha3 (e4309e90)
  - Platform: macOS

**Comment by LilliJane** [comment]
Is fixed in #348
