### ISSUE TITLE
Reorder `nerd job run` help text options

### ISSUE THREAD

**Issue by borismattijssen** [nerdalize/nerd#354]
## Expected Behavior
For `nerd job run -h`: Some options are more like "advanced options", these include `--kube-config`, `--timeout`, etc. Would be nice if they have a lower ordered ranking in the help text.

## Actual Behavior
Options that are mainly uninteresting to users are listed on the top of the help text. I find this confusing.

## Steps to Reproduce the Problem

  1. I think it would be neat to have another section in the help text that is called `Advanced options:`. I would place this between `Options:` and `Global Options:`. 

## Specifications

  - Version (using `nerd version`): 1.0.0-alpha3 (e4309e90)
  - Platform: macOS

**Comment by LilliJane** [comment]
In #348, I changed the order, but there is no section called `Advanced options`. I don't know if it will be sufficient enough, but it looks like that:
![image](https://user-images.githubusercontent.com/7657393/36972574-e671e25a-206f-11e8-95fa-1bc8695ef0f2.png)

**Comment by borismattijssen** [comment]
Awesome! The separate section is a nice would-have, but definitely not necessary if too much work. 

Thanks! 👍

**Comment by LilliJane** [comment]
![image](https://user-images.githubusercontent.com/7657393/37336500-db97cbc2-26b1-11e8-9032-880a650e4561.png)

In #371 I added the section `Advanced Options`
