### ISSUE TITLE
Overwriting an existing output dataset upon running a job

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#359]
## Expected Behavior
It is quite easy to overwrite an existing dataset by referencing in a job's output flag. When a user does this we would like to make sure this is not possible. It could be important data.

## Actual Behavior
It just overwrites it

**Comment by advanderveer** [comment]
An additional problem we've the job has been configured with this overwriting behaviour it can cause the retry mechanism to show weird behaviour as the second try now has an empty dataset.

**Comment by LilliJane** [comment]
I'm reopening this issue as I fixed the problem with the same name used for input and output datasets but it did not fix the general problem of data being overwritten
