### ISSUE TITLE
The `job log` hint in the job listing interface could be better

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#361]
## Expected Behavior
The current hint for logs in the job listing reads `To see the logs of a job, use: 'nerd job logs <JOB-NAME>'` but this might confuse people to think something went wrong. If we change it to something like `All you jobs are listed below, to see logs use: 'nerd job logs' `. This refers the use to the listing immediately

**Comment by LilliJane** [comment]
I updated the hint in #369, but I would be glad to get your opinion about it @advanderveer 
https://github.com/nerdalize/nerd/pull/369/files#diff-96d999c24a92f857fd7c67b513d7a881R66
