### ISSUE TITLE
Can't download output dataset openfoam on new nerd

### ISSUE THREAD

**Issue by rowanheijsteeg** [nerdalize/nerd#364]
The job
## Steps to Reproduce the Problem

  1. Just follow the https://feature-docs-update--nerdalize-website.netlify.com/applications/openfoam/ guide.
  2. Create folders on your system for input and for output. Use the input as given as example in the guide.

## Specifications

  - Version (using `nerd version`): 1.0.0-rc1
  - Platform: macOS
  - Subsystem: ?

## Anything else we need to know?
![screen shot 2018-03-06 at 16 35 43](https://user-images.githubusercontent.com/4026649/37041412-762e83f2-215c-11e8-9dd2-cc5fc93be2e6.png)

**Comment by LilliJane** [comment]
This issue is related to https://github.com/nerdalize/website/issues/205, so I'm closing this one
