### ISSUE TITLE
Dataset download should check first if the output directory is empty

### ISSUE THREAD

**Issue by LilliJane** [nerdalize/nerd#365]
## Expected Behavior

If my directory is not empty, I would expect the CLI to tell me so before it starts downloading anything.

## Actual Behavior

![image](https://user-images.githubusercontent.com/7657393/37042981-db2bea4e-215f-11e8-8230-e167b9c0a7a1.png)

## Steps to Reproduce the Problem

  1. Download a dataset to a non-empty dir

## Specifications

  - Version (using `nerd version`): 1.0.0-rc2 (611c6904)

**Comment by advanderveer** [comment]
Nice! LGTM
