### ISSUE TITLE
Unknown is misspelled as "unkown" in the pod state

### ISSUE THREAD

**Issue by Overv** [nerdalize/nerd#366]
## Expected Behavior

Unknown

## Actual Behavior

Unkown

See: https://github.com/nerdalize/nerd/blob/611c6904b2d6d6383be6120dfb5b99260a51bf11/cmd/job_list.go#L215

**Comment by LilliJane** [comment]
Fixed in https://github.com/nerdalize/nerd/commit/becebb6dbfec8f875eef30dad0b5a46bdb7e8429
