### ISSUE TITLE
Nerd job delete and dataset delete currently don't work properly

### ISSUE THREAD

**Issue by Overv** [nerdalize/nerd#374]
## Expected Behavior

Jobs and datasets are deleted shortly after running the `nerd job delete`/`nerd dataset delete` commands.

## Actual Behavior

Jobs are in the stage "Deleting" forever and datasets also just stick around.

## Steps to Reproduce the Problem

  1. Create a job/upload a dataset
  2. Delete it

## Specifications

  - Version (using `nerd version`): `1.0.0-rc2 (611c6904)`
  - Platform: Windows 10 x64
  - Subsystem: -

## Anything else we need to know?

Kubectl is able to remove both jobs and datasets just fine. A difference I noticed is that kubectl generally uses the background propagation policy whereas we use the foreground propagation policy. I'm not sure why it does not work with foreground propagation, especially because datasets do not have any dependents.

**Comment by LilliJane** [comment]
We're closing this issue as this seems to be fixed with fixing the duplicates kubernetes containers
