### ISSUE TITLE
Allow users to run private images

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#378]
## Expected Behavior
We would like to allow people to run jobs with a private image, a small design still needs to be hammered out but the initial idea is to add a flag to the job run command `--private` to  the job run command.

**Comment by LilliJane** [comment]
This will be done in several steps:

- [ ] By using `nerd job run --private <repo>/<image>`, a prompt will ask for a username and a (hidden) password. The image registry will be extracted from the image name (e.g `quay.io/<repo>/<image>` to `quay.io`, `<repo>/<image>` to `index.docker.io`). If some environment variables (names tbd) are provided, they will be used as username and password for the secret.
- [ ] If a secret is already set, people will have to choose between this secret or creating a new one. 
- [ ] If there are more than one secret, people will have to precise the name of the secret e.g `--private=<secret>`

**Comment by alexanderweiss** [comment]
Are we keeping track of which secret belongs to which hub/repo? That way the user won't need to specify the secret quite as often...

**Comment by LilliJane** [comment]
We could use the hub/repo/registry name as the secret name, @advanderveer do you know if there could be some edge cases?

**Comment by infernix** [comment]
@LilliJane one might have different secrets for different images within same registry

**Comment by LilliJane** [comment]
@infernix that's a valid point, we'll try to address it. Maybe instead of using the registry name as the secret name we could use the repository name, so people can have multiple secrets for a same registry
