### ISSUE TITLE
Flexvolumes  write space should be customizable

### ISSUE THREAD

**Issue by LilliJane** [nerdalize/nerd#392]
Right now, the flexvolumes have a hard coded `WriteSpace` variable, but it causes some issues as people need more space for their datasets.

It is possible to start by using quota. Indeed, if we add a label "flexvolume=X"(Go), we can have a more flexible setup, at least until we're able to provide private clusters.

When we'll have the private clusters, we could use flags or environment variable so that when we setup the flexvolume controller we can choose a specific size that will be used for this specific cluster only.

**Comment by advanderveer** [comment]
Current proposal is to read the flex volume size from the namespace's first (default) quota, the logic for this is already present and access to the kubernetes api is possible from the flex volume.
