### ISSUE TITLE
Can't run a job with specific private image 

### ISSUE THREAD

**Issue by infernix** [nerdalize/nerd#397]
## Expected Behavior

Should be able to run a private image with a version tag

## Actual Behavior
```
Error: failed to create secret: cluster failed to perform action: Secret "nlz-nerds-9vsrp" is invalid: metadata.labels: Invalid value: "xmr-stak:24586490076a87841243b887a9755417ba9ecbd5": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

## Steps to Reproduce the Problem

  1. `nerd job run --private --name=foo --vcpu=8  some.private.registry.nl/path/project::123456780versionorsha`

## Specifications

  - Version (using `nerd version`): 1.0.0-rc7
  - Platform: Linux
  - Subsystem:

## Anything else we need to know?

Looks like it tries to use the image name as label, but then fails to split on the colon if present (which it has to). Not sure what a good solution is. Relates to #378 and PR #384

**Comment by LilliJane** [comment]
Thanks for catching this bug! I started to work on a fix, it should be available soon
