### ISSUE TITLE
Make sure a private cluster is nerd ready

### ISSUE THREAD

**Issue by LilliJane** [nerdalize/nerd#411]
## Expected Behavior

When using `nerd cluster set-default X`, I expect to be able to run a job on this cluster.

## Actual Behavior

The private clusters are not setup to handle the nerd jobs, and `nerd job run` will create a forever pending job if datasets are used.

## Steps to Reproduce the Problem

  1. `nerd cluster set-default <some-private-cluster>
  1. `nerd job run --input=/a/directory:/input nerdalize/co2-calculator 30`

## Specifications

  - Version (using `nerd version`): 1.0.0-rc9

**Comment by advanderveer** [comment]
I had an interesting idea, I wonder what you think! How about we use the Kubernetes client to shoot in these resources but host the yaml somewhere on our domain. So people can do also do `kubectl create -f http://nerdalize.com/c.yaml`. The CLI would peform the same as the kubectl and download the spec and then create resources in there? Do you think this is easier or harder?
