### ISSUE TITLE
Nerd cli hangs on some api calls and doesn't show anything

### ISSUE THREAD

**Issue by neoel** [nerdalize/nerd#417]
Nerd calls authentication for listing the cluster in several cases. The endpoint is currently really slow (i've seen times up to 30 seconds).

## Expected Behavior
Since these calls are so slow, the cli appears to be hanging when using `nerd login`, `nerd cluster list` and `nerd cluster set-default|use`. 
I think it's nice to show the cli is doing stuff on the background

## Actual Behavior
Currently it's just blank, like the process hangs.

## Steps to Reproduce the Problem

  1. Login in using a nerdalize account shows this issue the most.

**Comment by LilliJane** [comment]
Same for catalog files fetching, a timeout should always be added (see https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779)
